### PR TITLE
Add lodestar api token for all networks

### PR DESCRIPTION
**Pull request by nflaig**
Add lodestar api token for mainnet and prater to match tokens in Lodestar prater and mainnet package

- https://github.com/dappnode/DAppNodePackage-Lodestar/blob/main/validator/security/api-token.txt
- https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/blob/main/validator/api-token.txt

### CODE REVIEW

**Comment by pablomendezroyo** [comment]
@nflaig  Should we add the token for `lodestar-gnosis` as well?

**Comment by nflaig** [comment]
@pablomendezroyo ideally yes, but at the moment there is only the prater and mainnet package for Lodestar. There package for gnosis chiado testnet (https://github.com/dappnode/DAppNodePackage-lodestar-chiado) but that is not updated either, i.e. it does not even specify an api token yet.

**Comment by nflaig** [comment]
@pablomendezroyo I also added the token for gnosis now, I quickly discussed this with @dsimog01 in telegram, all CLs use the same api token for all packages, we should align lodestar to follow the same approach. This way we can also already add the gnosis token even though the package does not exist yet.

**Review by dsimog01 — APPROVED** [review]

**Comment by pablomendezroyo** [comment]
> @pablomendezroyo I also added the token for gnosis now, I quickly discussed this with @dsimog01 in telegram, all CLs use the same api token for all packages, we should align lodestar to follow the same approach. This way we can also already add the gnosis token even though the package does not exist yet.

This makes sense for me

**Pull request merged**
